### ISSUE TITLE
Question: Requirements on Windows?

### ISSUE THREAD

**Issue by NickSeagull** [benoit-pierre/plover_midi#1]
What does one need to have installed in order to use this plugin?

I keep getting a "Python.h not found" errorv

Thanks in advance 😄

**Comment by benoit-pierre** [comment]
It's because no wheels are provided for the latest release of `python-rtmidi` on [PyPI](https://pypi.org/project/python-rtmidi/#files). As a temporary workaround, try running this command in a command prompt (from plover's install directory):
```cmd
plover_console.exe -s plover_plugins install "python-rtmidi==1.1.0"
```
Then try to install the `plover-midi` plugin again.

**Comment by NickSeagull** [comment]
Great, that worked, thanks!!

Maybe this will be useful for other users, would you accept a PR to add this to the readme? 😃

**Comment by benoit-pierre** [comment]
I'm hopping https://github.com/SpotlightKid/python-rtmidi/pull/36 is merged so the situation won't happen again. In fact, would you mind testing the resulting wheel work?
```
plover_console.exe -s plover_plugins install https://test-files.pythonhosted.org/packages/08/10/9420b406dfdea2fd5c6f824205fe2c8ea842578530bbb66f96fedc0014e9/python_rtmidi-1.1.1-cp36-cp36m-win32.whl
```

**Comment by NickSeagull** [comment]
Looks like that worked also

**Comment by benoit-pierre** [comment]
Good, thanks for testing.

**Comment by NickSeagull** [comment]
So, should I create the PR or shall we just close this and wait until this goes upstream?

**Comment by benoit-pierre** [comment]
Let's keep this issue open until the situation is resolved.

**Comment by benoit-pierre** [comment]
Windows and macOS wheels for `python-rtmidi` are now available.
